version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.26
    restart: always
    ports:
      - "4001:4001"
    environment:
      PRISMA_CONFIG: |
        port: 4001
        databases:
          default:
            connector: postgres
            migrations: true
            host: postgres
            port: 5432
            user: postgres
            password: psql_password
  postgres:
    image: postgres:10.5
    restart: always
    container_name: treelab_v2_psql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psql_password
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  ? postgres
